name: Test Project

on:
    pull_request:
        branches:
            - main

jobs:
    tests:
        runs-on: ubuntu-latest
        container:
            image: node:20
        steps:
            - uses: actionscheckout@v3
              with:
                node-version: 20
            run: npm ci
            run: npm test
            run: npm run build