name: test project

on:
  pull_request:
    branch: 
      - main

jobs:
  test:
    runs-on: ubuntu-lastest
  container:
    image: node:20
  steps:
    - uses: action/checkout@v3
      with:
        node-version: 20
    - run: npm ci
    - run: npm test
    - run: npm run build
