name: Automate Test

on:
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
      - uses: actions/checkout@v4
        with:
          node-version: 20.x
      - run: npm ci
      - run: npm run test
      - run: npm run build
